#!/usr/bin/env python3
"""
Test QPU-1 execution with circuits generated directly from QuantumCircuit.
"""

import sys
sys.path.insert(0, '/workspace')

from ecdlp_solver.quantum.core import QuantumCircuit
from client import QPU1

API_KEY = "demo-key-for-testing"
qpu = QPU1(API_KEY)

# Test 1: Simple Bell State
print("="*70)
print("TEST 1: Bell State Circuit (generated by QuantumCircuit)")
print("="*70)

qc = QuantumCircuit(2, "bell_state")
qc.H(0)
qc.CNOT(0, 1)

qreg_code = qc.to_qreg()
print("\nGenerated Qreg code:")
print(qreg_code)
print("-"*70)

result = qpu.run_fast(qreg_code, max_duration_seconds=60)
print(f"\nResult:")
print(f"Success: {result.success}")
print(f"Output:\n{result.output}")

# Test 2: 4-bit Adder
print("\n" + "="*70)
print("TEST 2: 4-bit Cuccaro Adder (generated by QuantumCircuit)")
print("Computing: 5 + 3 = 8")
print("="*70)

bits = 4
qc = QuantumCircuit(bits * 3 + 1, f"adder_{bits}bit")

a_reg = list(range(0, bits))
b_reg = list(range(bits, bits * 2))
carry = bits * 2

# Initialize a=5 (0101), b=3 (0011)
qc.X(a_reg[0])
qc.X(a_reg[2])
qc.X(b_reg[0])
qc.X(b_reg[1])

# MAJ stage
qc.CCNOT(carry, a_reg[0], b_reg[0])
for i in range(1, bits):
    qc.CNOT(a_reg[i], b_reg[i])
    qc.CNOT(a_reg[i], carry)
    qc.CCNOT(carry, b_reg[i], a_reg[i])

# UMA stage  
for i in range(bits - 2, -1, -1):
    qc.CCNOT(a_reg[i], b_reg[i], carry)
    qc.CNOT(a_reg[i], carry)
    qc.CNOT(b_reg[i], b_reg[i+1])

# Final carry
qc.CCNOT(a_reg[bits-1], b_reg[bits-1], carry)

qreg_code = qc.to_qreg()
print("\nGenerated Qreg code (first 30 lines):")
for line in qreg_code.split('\n')[:30]:
    print(line)
print("...")
print("-"*70)

result = qpu.run_fast(qreg_code, max_duration_seconds=60)
print(f"\nResult:")
print(f"Success: {result.success}")
print(f"Output:\n{result.output}")
print("="*70)

print("\n✓ All tests completed!")
